backend:
  name: git-gateway
  repo: "tutdewiguna/tutde-portfolio"
  branch: main

media_folder: "img/blog-page"
public_folder: "/img/blog-page"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog" 
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", hint: "Deskripsi singkat untuk SEO dan preview artikel." }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }